### ISSUE TITLE
explicit payload handler invocation and form submit

### ISSUE THREAD

**Issue by bazo** [vojtech-dobes/nette.ajax.js#100]
please add a way to expliciyly call the payload handler from outside so we can do

```
$.get(url, function(payload){
    $.nette.success(payload)
})
```

that's very useful when other js components. the old jquery.nette.js had this functionality

 also an explicit form submit, like jquery.ajaxform.js would be helpful.

**Comment by echo511** [comment]
A question to this topic. If I have 3rd party JS component that has its own way with AJAX, how can I triger success event? I edited this extension as bazo suggested and used in my plugin like this: https://github.com/echo511/Plupload/blob/cd026db8d3b449c1c6b80a6278e06b66288a7a59/src/Echo511/Plupload/templates/control/plupload.latte#L34

Could this be supported natively?
