### ISSUE TITLE
Remove ignore of `extensions/*` from bower.json

### ISSUE THREAD

**Issue by fprochazka** [vojtech-dobes/nette.ajax.js#111]
Hi, I'd like to propose [removing of this line](https://github.com/vojtech-dobes/nette.ajax.js/blob/6a9ca698e58c27c45edcbfd448771eafbd7f3910/bower.json#L7) from `bower.json`. Why was it introduced?

**Comment by solcik** [comment]
+1

**Comment by vojtech-dobes** [comment]
I thought it's too much to get it installed immediatelly.

**Comment by fprochazka** [comment]
The fidRemove and some others are really nice. It's just a few lines of code that you don't have to use. I would call this "extreme minimalism" - it's doing more bad than good.
