### ISSUE TITLE
how to use extenison scrollTo.ajax.js?

### ISSUE THREAD

**Issue by chemix** [vojtech-dobes/nette.ajax.js#112]
Hi, I can not find any word how to use this extension. Is it possible add some "examples" folder and add some example how work with this extension ( and others too, like ga, etc...)

thanks

**Comment by fprochazka** [comment]
It should work automagically. Simply put - it scrolls to the first returned snippet. There is no way to control it.

**Comment by chemix** [comment]
I just put extenison to html?  No data atribut for activating is necessary? ... auto scrolling for all or nothing?

**Comment by fprochazka** [comment]
To what html? You mean include it in page? - Yes. I just looked at the code and figured it from the 10 lines it have. I bet you could do the same. There are no attributes - it's really naive :) 

If you don't like that and have a better idea, I think a pullrequest would be nice :)

**Comment by fprochazka** [comment]
To what html? You mean include it in page by script tag? - Yes, if that's how you add scripts to the page. Also, you should do it before the ajax is initialized, as with all the extensions.

I just looked at the code and figured it from the 10 lines it have. I bet you could do the same. There are no attributes - it's really naive :) 

If you don't like that and have a better idea, I think a pullrequest would be nice :)

**Comment by chemix** [comment]
:+1:

**Comment by mishak87** [comment]
Actually just copy paste or merge used extensions to one file. Separating them to tiny is heresy.

**Comment by lukasojd** [comment]
+1
