### ISSUE TITLE
IE8 error when submitting form: Object doesn't support this action

### ISSUE THREAD

**Issue by janedbal** [vojtech-dobes/nette.ajax.js#119]
Error is raised when you submit ajaxifized form for the second time (form was re-rendered by snippet replacement). Problem is on [this line](https://github.com/vojtech-dobes/nette.ajax.js/blob/2eaf1d6261ee4b6442dcd099cc1223557aad212a/nette.ajax.js#L320) as it was previously reported on [nette forum](https://forum.nette.org/cs/11005-nette-ajax-js-alt-obsluha-pro-ajax-s-jquery?p=15#p157096).

How to reproduce:
- download [WinXP/IE8](https://dev.modern.ie/tools/vms) virtual machine and load it (I can't reproduce it in emulated IE8 in devtools)
- download nette sandbox, load nette.ajax.js, init it
- wrap page to `content` snippet
- create following form, place it to snippet and submit it twice

``` php
$form = new \Nette\Application\UI\Form();
$form->addSubmit('send');
$form->getElementPrototype()->addClass('ajax');
$form->onSuccess[] = function ($form) {
    $this->redrawControl('content');
};
```

**Comment by janedbal** [comment]
Oh, now I see that the original problem is #75 and people were reporting the same thing as I'm in comments of commit b96243f35b58c880dd1fad2778395a08a8193c69. The proposed solution works, may I send PR?


Working fix:
```js
if (validate.form && analyze.form && !((analyze.isSubmit || analyze.isImage) && analyze.el.attr('formnovalidate') !== undefined)) {
    var ie = this.ie();
    if ((typeof ie === 'undefined' || ie >= 9)) {
        if (analyze.form.get(0).onsubmit && analyze.form.get(0).onsubmit(e) === false) {
            e.stopImmediatePropagation();
            e.preventDefault();
            return false;
        }
    }
}
```

**Comment by vojtech-dobes** [comment]
I think this has been fixed long time ago.
