### ISSUE TITLE
Package depends on nette-forms 2.2

### ISSUE THREAD

**Issue by camohub** [vojtech-dobes/nette.ajax.js#127]
Hi, is there a reason why nette,ajax.js has not allowed higher version of nette-forms?  
There si "nette-forms": "~2.2"

**Comment by vojtech-dobes** [comment]
I've dropped the dependency completely in https://github.com/vojtech-dobes/nette.ajax.js/commit/3f790b85417b63e7ac231bca38e67acf14d64a4c: it should be independent decision whether website uses nette forms validation or not, nette.ajax.js should neither enforce it nor require specific version.
