### ISSUE TITLE
Plugins not executed on $.nette.ajax({ url: ... );

### ISSUE THREAD

**Issue by dakorpar** [vojtech-dobes/nette.ajax.js#131]
When redirecting user with   $.nette.ajax I saw that address bar doesn't change, after some investigation I realized plugins are not executed when calling directly $.nette.ajax
Or am I doing something wrong? how to redirect user using nette.ajax?

**Comment by vojtech-dobes** [comment]
Could you please clarify more what you are trying to achieve? I am not sure if I understand.

**Comment by dakorpar** [comment]
So if I execute this particular code:

`$.nette.ajax({ url: 'someUrl' });`

I've noticed that address bar is not changing to  'someUrl', after more investigation I realized none of nette.ajax plugins are executed if I call `$.nette.ajax({ url: 'someUrl' });` directly in code, and not just setting attribute class to ajax

**Comment by dakorpar** [comment]
I'm closing since I'm no longer using this extension and it passed 3,5 years since last activity
