### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by xificurk** [vojtech-dobes/nette.ajax.js#137]
First step towards npm support was done in #130, which introduced `package.json`, but that's not enough...
The package should be published in npm registry, that in my opinion should be done rather by the author than someone else.
Furthermore, the version string should be bumped to 2.2.0.

**Comment by Trejjam** [comment]
Hi, I miss this issue and add npm package couple weeks ago. Could author tell me what is his nick-name on NPM? I also create pull request to package.json v2.2.0 #140

**Comment by vojtech-dobes** [comment]
@Trejjam Hi, thanks for the initiative. My username is `vojtechdobes`.

**Comment by Trejjam** [comment]
@vojtech-dobes Hi, you are added

**Comment by xificurk** [comment]
This is already done... closing.

**Comment by jetelusmaximus** [comment]
Hello, I would like to follow up on this issue to suggest stands for source and distribution: folders src/ and dist/.
What do you think about it? Thanks.

**Comment by trejjam** [comment]
Hi, reusing issue is not good idea.

**Comment by jetelusmaximus** [comment]
Ok, thank you for quick reply.
