### ISSUE TITLE
Multiple $.nette.ajax() are cancelled

### ISSUE THREAD

**Issue by medhi** [vojtech-dobes/nette.ajax.js#142]
As you can see on http://codepen.io/anon/pen/MpJNqz,
if I call `$.nette.ajax()` more than once, only last call is successful. All previous ones are cancelled. 
Am I doing something wrong or is it a bug?

**Comment by uestla** [comment]
@medhi It's actually the `'unique'` extension which is turned on by default.

https://github.com/vojtech-dobes/nette.ajax.js/blob/master/nette.ajax.js#L512-L523

But you can disable it - `$.nette.ext('unique', null)`.

**Comment by medhi** [comment]
Oh, thanks! What is the unique extension for?

**Comment by uestla** [comment]
As I understand it it's when you click on a button but change your mind and click on another one before the previous request completes...

**Comment by vojtech-dobes** [comment]
If you find this behavior useful and want to disable it only for certain calls/elements, it's also possible:

```js
$.nette.ajax({
    url: ...,
    off: ['unique']
});
```

```html
<a href="..." data-ajax-off="unique"></a>
```

You can put this data attribute on any ajaxified element (form, button...).

**Comment by medhi** [comment]
@vojtech-dobes That's the best, thanks!
