### ISSUE TITLE
NPM/Yarn outdated

### ISSUE THREAD

**Issue by aleswita** [vojtech-dobes/nette.ajax.js#145]
NPM/Yarn packages haven't current version of library

https://www.npmjs.com/package/nette.ajax.js
https://yarnpkg.com/en/package/nette.ajax.js

**Comment by aleswita** [comment]
ping

**Comment by jelen07** [comment]
How it's going? @vojtech-dobes  @Trejjam

**Comment by trejjam** [comment]
Updated to v2.3.0

**Comment by aleswita** [comment]
tnx
